development: &default
  adapter: postgresql
  host: localhost
  username: davidmoore
  database: <%= ENV.fetch("APP_NAME") %>_dev
  timeout: 5000

test:
  <<: *default
  database: <%= ENV.fetch("APP_NAME") %>_test

staging:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>